### PR TITLE
Fix hash mismatch with yawsso version 0.7.2

### PR DESCRIPTION
**Pull request by SergeyMokhov**
Fix for hash mismatch described in issue #2

### CODE REVIEW

**Review by IevgeniiB — APPROVED** [review]
🙏🏻

**Comment by pguillebert** [comment]
Hi! can we merge this PR? the homebrew install is still broken. Thank you 🙏

**Comment by SergeyMokhov** [comment]
> 🙏🏻

You are the only one with write permission for the repo, could you merge please?

**Comment by IevgeniiB** [comment]
> > 🙏🏻
> 
> You are the only one with write permission for the repo, could you merge please?

@SergeyMokhov If this is addressed to me (judging from the emoji) - I don't. I think everyone has "approve" permissions 🤷🏻

**Comment by SergeyMokhov** [comment]
@IevgeniiB  in order for my changes to be available to people who installed yawsso using your repository, someone with **write** permissions to your repository have to merge my pull request into your repository master branch. At the moment, I believe it is just you.

> [How to merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request) 
> [Repository permissions](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository)

**Comment by IevgeniiB** [comment]
@SergeyMokhov It is not my repository. I believe it belongs to @syncdk. Please direct your questions to them.

**Comment by SergeyMokhov** [comment]
@IevgeniiB Sorry my friend, your are right.
> @SergeyMokhov It is not my repository. I believe it belongs to @syncdk. Please direct your questions to them.

@syncdk  could you please merge?

**Comment by Systemmanic** [comment]
Sorry for the delay in getting this merged. Life stuff.

**Comment by SergeyMokhov** [comment]
> Sorry for the delay in getting this merged. Life stuff.

@syncdk Whatever it is, I hope everything gets better sooner 🙏

**Comment by Systemmanic** [comment]
~Hold up this is actually wrong.~ Nope, it was right.

**Comment by Systemmanic** [comment]
> > Sorry for the delay in getting this merged. Life stuff.
> 
> @syncdk Whatever it is, I hope everything gets better sooner 🙏

Thank you my friend, and appreciate your patience while I butchered this update 😆

**Pull request merged**
